modLoader="javafml"

loaderVersion="[40,)"

license="All rights reserved"

[[mods]]
modId="turorudi"

version="0.1-20220714"

displayName="TuroRudi"

logoFile="logo.png"

credits="Forge, Svitlogorie, B.YU. Alexandrov, Vkusnoteevo, Vologosha, Kaupenjoe"

authors="OleSTEEP"

description='''
This mod add to game TuroRudi
'''

[[dependencies.turorudi]]

    modId="forge"

    mandatory=true

    versionRange="[40,)"

    ordering="NONE"

    side="BOTH"

[[dependencies.turorudi]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
