modLoader="javafml"

loaderVersion="[41,)"

license="All rights reserved"

[[mods]]
modId="turorudi"

version="0.4.3"

displayName="TuroRudi"

logoFile="logo.png"

credits="Forge, B.YU. Alexandrov, Cow from Corenovka, Pöttyös, Preobrajenskiy, Rostagroexport, Svitlogorie, Vkusnoteevo, Vologosha, Kaupenjoe"

authors="OleSTEEP"

description='''
Minecraft mod that adds delicious treats to the game - curd snacks.
'''

[[dependencies.turorudi]]

    modId="forge"

    mandatory=true

    versionRange="[41,)"

    ordering="NONE"

    side="BOTH"

[[dependencies.turorudi]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
